name: Ember-Table CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      - name: "Install StepSecurity Action"
        id: step_security
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install mise and tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
        with:
          install: true
          cache: true
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test:ember
        env:
          CI: true

  test-ember-try:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        ember-version:
          [
            embroider-safe,
            # embroider-optimized,
            ember-lts-5.12,
            ember-lts-6.4,
            ember-release,
            # ember-production,
            ember-default-docs
          ]

    steps:
      - name: "Install StepSecurity Action"
        id: step_security
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install mise and tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c
        with:
          install: true
          cache: true
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Tests
        run: npx ember try:one ${{ matrix.ember-version }} --skip-cleanup
